/**
 * AUTO-GENERATED by pkm/scripts/export-portfolio-work.mjs
 * Source: wiki/projects/tylermiranda-com/portfolio-work.md
 * Do not edit by hand — update the PKM feed and re-run the export.
 * Local preview only; do not deploy unless explicitly requested.
 */

export interface WorkProject {
  id: string;
  title: string;
  summary: string;
  tech: string[];
  github?: string;
  url?: string;
  linkNote?: string;
}

export interface WorkLogEntry {
  date: string;
  text: string;
}

export const workProjects: WorkProject[] = [
  {
    "id": "podly-pure-podcasts",
    "title": "Podly Pure Podcasts",
    "summary": "Fork and actively develop a self-hosted podcast ad-removal stack: LLM segment classification, ffmpeg cuts, per-feed prompts, correction feedback loop, and UI/ops fixes. Public feeds behind Cloudflare Tunnel/Access with WAF rules for picky clients.",
    "tech": [
      "Python",
      "Docker",
      "Cloudflare",
      "Whisper ASR",
      "LM Studio",
      "React"
    ],
    "github": "https://github.com/tylermiranda/podly_pure_podcasts",
    "url": "https://pods.tylermiranda.com"
  },
  {
    "id": "speakr",
    "title": "Speakr + Speakr Companion",
    "summary": "Customize Speakr (OIDC SSO, tag-driven summaries, remote Whisper) and actively develop Speakr Companion—a macOS menu-bar app that auto-records Zoom via Core Audio and uploads to the Speakr API.",
    "tech": [
      "Docker",
      "OIDC",
      "Whisper ASR",
      "macOS",
      "Core Audio",
      "Cloudflare Access"
    ],
    "github": "https://github.com/murtaza-nasir/speakr"
  },
  {
    "id": "sedgwick-property-tax",
    "title": "CountyComps",
    "summary": "Actively building a guided web MVP that turns uploaded county property PDFs into a code-built hearing exhibit (worksheet, arithmetic, speaking notes)—LLM extract, deterministic packet assembly on Cloudflare Workers (Hono, React, D1/R2/KV).",
    "tech": [
      "Cloudflare Workers",
      "Hono",
      "React",
      "D1",
      "R2",
      "KV"
    ],
    "linkNote": "private / in development"
  }
];

export const workLog: WorkLogEntry[] = [
  {
    "date": "2026-08-24",
    "text": "Podly transcript mark UX + learn-from-corrections plan; Speakr Companion Recent Recordings / Dock icon / timezone fixes; CountyComps Grok Bot CI team prompts."
  },
  {
    "date": "2026-08-21",
    "text": "Speakr Companion Zoom auto-record via global Core Audio tap; Krisp-replacement cutover."
  },
  {
    "date": "2026-08-20",
    "text": "Speakr setup/ops review (prompts and recording path)."
  },
  {
    "date": "2026-08-19",
    "text": "Speakr server-side recording + meeting tag templates; Podly Tower overlay fix + deploy."
  },
  {
    "date": "2026-08-18",
    "text": "CountyComps plain-language / appeal-process product copy."
  },
  {
    "date": "2026-08-17",
    "text": "CountyComps MVP + Cloudflare D1/R2/KV resources."
  },
  {
    "date": "2026-08-14",
    "text": "Speakr Pocket-ID OIDC SSO and tag/naming templates."
  },
  {
    "date": "2026-08-12",
    "text": "Podly automated ad-review loop + LM Studio bootstrap."
  },
  {
    "date": "2026-08-11",
    "text": "Podly fork image deploy + YouTube Music Cloudflare WAF fix."
  }
];
